apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: musicplayer
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/HubaBoy/musicPlayer
    path: k8s
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true