# Build stage
FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./

# по-стабилно за CI/CD
RUN npm ci

COPY . .

RUN npm run build


# Production stage
FROM nginx:alpine

# Vite output folder = dist ✔
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]